[package]
name = "sanvi"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.5"
atom_syndication = "0.12.4"
clap = "4.5.20"
eyre = "0.6.12"
log4rs = "1.3.0"
minijinja = "2.3.1"
rss = "2.0.9"
scraper = "0.20.0"
tokio = "1.40.0"
